### ISSUE TITLE
Sierra EM9190 doesn't works

### ISSUE THREAD

**Issue by wigcheng** [kristrev/mhi-for-kernel-4.14#1]
Hello, as title, that module also use PCIE interface, and I port your driver to my ARM64 device.
Could you provide qmicli command for MHI interface? My device nodes are
/dev/mhi0_QMI
/dev/wwan0p1QCDM
/dev/wwan0p2MBIM

but got error message using qmicli command:
qmicli -d /dev/mhi0_QMI --wda-get-data-format
[01 Apr 2020, 17:24:37] -Warning ** [/dev/mhi0_QMI] couldn't detect transport type of port: couldn't detect device driver
error: couldn't open the QmiDevice: Cannot automatically select QMI/MBIM mode

BTW, network interface is existed:
mhi_hwip0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 16384
        inet6 fe80::200:ff:fe00:0  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Thanks

**Comment by kristrev** [comment]
Hi @wigcheng,

Thanks for letting me know someone is using this backport :) I don't have access to the EM9190, but when I used `qmicli` for testing the driver I had to add the `--device-open-qmi` argument. So for example: `qmicli -d /dev/mhi0_QMI --device-open-qmi --wds-get-packet-service-status`.

By the way, I know what I wrote in the `README`, but I have unfortunately not had any time to keep the 4.14 backport up to date. The reason is that the project that I am involved in and where pci modems are used is moving to kernel 5.4 (next OpenWrt). I have a backport to 5.4 ready and plan to create a second repo once it is out.

**Comment by wigcheng** [comment]
Wow, that will very useful for me, my current kernel is 5.4.70 and 5.10.35, so I ported your 4.14 driver to my kernel and merged it manually at this moment, maybe I missing something?

Just tested your command but still failed:
# qmicli -d /dev/mhi0_QMI --device-open-qmi --wds-get-packet-service-status
[01 Apr 2020, 18:58:51] -Warning ** [/dev/mhi0_QMI] couldn't detect transport type of port: couldn't detect device driver
[01 Apr 2020, 18:58:51] -Warning ** [/dev/mhi0_QMI] requested QMI mode but unexpected transport type found
error: couldn't create client for the 'wds' service: CID allocation failed in the CTL client: Transaction timed out

Any suggestion? :(

In addition, I found latest upstream kernel has mhi_wwan_ctrl option, and I saw some article has mhitty node but I cannot find the driver source code, so should be no need those drivers?

Thanks for your help!!!!

**Comment by kristrev** [comment]
@wigcheng Hm, what if you try MBIM (just for fun)? I know that my company has ordered EM9190, so hopefully I should be able to test it soon.

I will update this issue when I have published my backport.

**Comment by wigcheng** [comment]
MBIM also tested before but failed: 
[01 Apr 2020, 17:24:54] -Warning ** [/dev/mhi0_QMI] couldn't detect transport type of port: couldn't detect device driver
[01 Apr 2020, 17:24:54] -Warning ** [/dev/mhi0_QMI] requested MBIM mode but unexpected transport type found
[01 Apr 2020, 17:24:54] -Warning ** [/dev/mhi0_QMI] Couldn't find udev device
[01 Apr 2020, 17:24:54] -Warning ** [/dev/mhi0_QMI] Couldn't get descriptors file path
error: couldn't open the QmiDevice: Operation timed out: device is closed

BTW, my qmicli version is 1.26.4, do I need upgrade?

OK, I look forward your update, thanks a lot!

**Comment by wigcheng** [comment]
Okay! I think the problem should be utilities version, check with modemmanager official repo, my current is 1.14, there's no support MHI interface, but latest 1.18 version did it, I'll update modemmanager and qmicli and test again.

Thanks, I'll close it first.

**Comment by kristrev** [comment]
I put the 5.4 backport [here](https://github.com/kristrev/mhi-for-kernel-5.4).

**Comment by wigcheng** [comment]
Thanks a lot, I’ll try it on Saturday, I’ll get vaccinated tomorrow, need rest several days.

Hope it works.
